modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Vazkii/Neat"

[[mods]]
modId="neat"
displayName="Neat"
version="GRADLE:VERSION-GRADLE:BUILD"
authors="Vazkii"
description='''
Minimalistic Functional Unit Plates for the modern Minecrafter
'''
